#!/bin/bash

gen_id() {
	perl -MTime::HiRes=time -E '
		my $t = time * 10**5;
		my @nums = (0..9,"a".."z","A".."Z");
		sub convert {
			my $n = shift;
			my $c;
			while($n > 0) {
				$c = $nums[$n % @nums] . $c;
				$n = int($n/@nums)
			}
		$c
	}
	printf "%09s%04s", convert($t), convert(rand 16_777_215)'
}

path=$(readlink -f $0)

source "$(dirname $path)/git-issue-edit-msg"
source "$(dirname $path)/git-issue-edit-title"
source "$(dirname $path)/git-issue-ls"
source "$(dirname $path)/git-issue-new"
source "$(dirname $path)/git-issue-pull"
source "$(dirname $path)/git-issue-push"
source "$(dirname $path)/git-issue-reply"
source "$(dirname $path)/git-issue-show"
source "$(dirname $path)/git-issue-sync"

$1 ${@:2}
