#!/bin/bash

close() {
    local force=0
    while [ $# -gt 0 ]; do
        case "$1" in
            -f|--force) force=1; shift ;;
            *) break ;;
        esac
    done

    local iss_id
    local status_file
    local sha1_status
    local tree
    local sha1_tree
    local parent
    local commit_hash

    iss_id=$(iss-id "open" $1)

    local ref="refs/issues/$iss_id"
    local path="status"

    git show-ref --verify --quiet "$ref" || die "Not a valid issue id"

    if [ "$force" -eq 0 ]; then
        printf "Close issue %s? [y/N] " "$iss_id"
        read -r ans
        case "$ans" in
            y|Y|yes|YES|Yes) ;;
            *) die "Aborted" ;;
        esac
    fi

    status_file=$(mktemp)
    echo "closed" > $status_file

    sha1_status=$(git hash-object -w $status_file)

    tree=$(mktemp)
    git ls-tree $ref | grep -v "$path$" > $tree
    echo "100644 blob $sha1_status	$path" >> $tree

    sha1_tree=$(git mktree < $tree)
    parent=$(git show-ref --verify --hash "$ref")

    commit_hash=$(echo "Issue closed: ($iss_id)" | git commit-tree $sha1_tree -p $parent)

    git update-ref refs/issues/$iss_id $commit_hash

    echo "$iss_id"
}
