#!/bin/bash

new() {
    local title="$@"

    if [ -z "$title" ]; then
	echo -n "Issue title: "
	read title
    fi

    debug "title: $title"
    local sha1_title=$(printf %s "$title" | git hash-object -w --stdin)
    debug "sha1_title: $sha1_title"

    local sha1_status=$(git hash-object -w <(echo "open"))
    debug "sha1_status: $sha1_status"

    local message_file=$(mktemp)
    "${EDITOR:=${VISUAL:-vi}}" $message_file
    debug-cat $message_file

    local msg_id=$(gen_id)
    local sha1_msg=$(git hash-object -w $message_file)

    local msgs_tree=$(mktemp)

    echo "100644 blob $sha1_msg	$msg_id" > $msgs_tree
    debug-cat $msgs_tree

    local sha1_msgs_tree=$(git mktree < $msgs_tree)

    local tree=$(mktemp)

    echo "100644 blob $sha1_title	title"   > $tree
    echo "100644 blob $sha1_status	status" >> $tree
    echo "040000 tree $sha1_msgs_tree	msgs"   >> $tree
    debug-cat $tree

    local sha1_tree=$(git mktree < $tree)

    local commit_hash=$(echo "Issue created: $title ($msg_id)" | git commit-tree $sha1_tree)

    git update-ref refs/issues/$commit_hash $commit_hash

    echo $commit_hash
}
