#!/bin/bash

gen_id() {
	perl -MTime::HiRes=time -E '
		my $t = time * 10**5;
		my @nums = (0..9,"a".."z","A".."Z");
		sub convert {
			my $n = shift;
			my $c;
			while($n > 0) {
				$c = $nums[$n % @nums] . $c;
				$n = int($n/@nums)
			}
		$c
	}
	printf "%09s%04s", convert($t), convert(rand 16_777_215)'
}

source "$(dirname $0)/git-issue-$1"

$1 ${@:2}
