#!/bin/bash

edit-title() {
    local iss_id=$(iss-id "open" $1)

    local ref="refs/issues/$iss_id"
    local path="title"

    local title_file=$(mktemp)
    git show $ref:$path > $title_file
    [ -s $title_file ] || die "Not a valid issue id"

    "${EDITOR:=${VISUAL:-vi}}" $title_file
    local sha1_title=$(git hash-object -w $title_file)


    local tree=$(mktemp)
    git ls-tree $ref | grep -v "$path$" > $tree
    echo "100644 blob $sha1_title	$path" >> $tree

    local sha1_tree=$(git mktree < $tree)
    local parent=$(git show-ref --verify --hash "$ref")

    local commit_hash=$(echo "Title edited: ($iss_id)" | git commit-tree $sha1_tree -p $parent)

    git update-ref refs/issues/$iss_id $commit_hash

    echo "$iss_id"
}
