#!/bin/bash

ls() {
	local status="$1"
	git for-each-ref --format="%(refname)" refs/issues/ | while read ref; do
		local ID=$(echo $ref | perl -nalE 'say $1 if m{([^/]+?)$}')
		echo $(git log --pretty=format:"%ct $ref %h" $ID -- 2> /dev/null || echo "0 $ref $ID")
	done | sort | while read _ ref ID; do
		local title=$(git show $ref:title)
		local curr_status
		curr_status="$(git show $ref:status)"
		if [ -z "$status" ] || [ "$curr_status" = "$status" ]; then
			printf "%s - %s\n" $ID "$title"
		fi
	done
	return 0
}
