#!/bin/bash

status() {
    local iss_id
    local status_str
    local status_file
    local sha1_status
    local tree
    local sha1_tree
    local parent
    local commit_hash

    iss_id=$(iss-id "--all" $1)
    status_str="$2"

    [ -z "$status_str" ] && die "Status not specified"

    local ref="refs/issues/$iss_id"
    local path="status"

    git show-ref --verify --quiet "$ref" || die "Not a valid issue id"

    status_file=$(mktemp)
    echo "$status_str" > $status_file

    sha1_status=$(git hash-object -w $status_file)

    tree=$(mktemp)
    git ls-tree $ref | grep -v "$path$" > $tree
    echo "100644 blob $sha1_status	$path" >> $tree

    sha1_tree=$(git mktree < $tree)
    parent=$(git show-ref --verify --hash "$ref")

    commit_hash=$(echo "Issue status: $status_str ($iss_id)" | git commit-tree $sha1_tree -p $parent)

    git update-ref refs/issues/$iss_id $commit_hash

    echo "$iss_id"
}
