#!/bin/bash

edit-msg() {
    local iss_id=$(iss-id "open" $1)

    local ref="refs/issues/$iss_id"
    local msg_no=-1
    if [ -z "$2" ]; then
	show $iss_id
	echo "Message number: "
	read msg_no
    else
	msg_no=$2
    fi
    [ "$msg_no" -lt 0 ] && die "Message number invalid"

    local path=$(git ls-tree --name-only "$ref" msgs/ | while read path; do
	msg_no=$(( $msg_no - 1 ))
	[ "$msg_no" -eq 0 ] && echo $path
    done)

    [ -z "$path" ] && die "Message number invalid"

    local msg_id=$(echo $path | perl -palE 's{msgs/}{}')

    local message_file=$(mktemp)
    git show $ref:$path > $message_file

    "${EDITOR:=${VISUAL:-vi}}" $message_file
    local sha1_msg=$(git hash-object -w $message_file)

    local msgs_tree=$(mktemp)
    git ls-tree "$ref" msgs/ | grep -F -v -- "$path" | perl -palE 's{\tmsgs/}{\t}' > "$msgs_tree"

    echo "100644 blob $sha1_msg	$msg_id" >> $msgs_tree

    local sha1_msgs_tree=$(git mktree < $msgs_tree)

    local tree=$(mktemp)
    git ls-tree refs/issues/$iss_id | grep -v "\tmsgs$" > $tree

    echo "040000 tree $sha1_msgs_tree	msgs" >> $tree

    local sha1_tree=$(git mktree < $tree)

    local parent=$(git show-ref --verify --hash "$ref")
    local commit_hash=$(echo "Reply edited: ($msg_id)" | git commit-tree $sha1_tree -p $parent)

    git update-ref refs/issues/$iss_id $commit_hash

    echo "$msg_id"
}
